name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip project
        run: unzip DLinkRouterApp.zip -d DLinkRouterApp

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ننزّل Gradle ونفعّله
      - name: Install Gradle 8.7
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle -v

      - name: Build with Gradle
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle -p DLinkRouterApp assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: DLinkRouterApp
          path: DLinkRouterApp/app/build/outputs/apk/debug/app-debug.apk
